server:
  port: 8081
  servlet:
    context-path: /
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    #是否使用内置的MQ， true  使用； fale  不使用
    in-memory: false
    #是否在回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    non-blocking-redelivery: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///07work?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    suffix: .html
    prefix: /
  jpa:
    show-sql: true
  mail:
    host: smtp.qq.com     #如果是163邮箱就把qq换为163
    username: 961033552@qq.com
    password: rmjlfflwevvsbdgc
mybatis:
  mapper-locations: /mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

my_queue: myqueue
